/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XExplorerRouteImport } from './routes/x-explorer'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrsRouteImport } from './routes/prs'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AgentProductivityRouteImport } from './routes/agent-productivity'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as TimelineIndexRouteImport } from './routes/timeline/index'
import { Route as WorkSplatRouteImport } from './routes/work/$'
import { Route as TimelineHourlyRouteImport } from './routes/timeline/hourly'
import { Route as JiraPriorityRouteImport } from './routes/jira/priority'
import { Route as JiraBoardsRouteImport } from './routes/jira/boards'

const XExplorerRoute = XExplorerRouteImport.update({
  id: '/x-explorer',
  path: '/x-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsRoute = PrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentProductivityRoute = AgentProductivityRouteImport.update({
  id: '/agent-productivity',
  path: '/agent-productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/timeline/',
  path: '/timeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSplatRoute = WorkSplatRouteImport.update({
  id: '/work/$',
  path: '/work/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineHourlyRoute = TimelineHourlyRouteImport.update({
  id: '/timeline/hourly',
  path: '/timeline/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraPriorityRoute = JiraPriorityRouteImport.update({
  id: '/jira/priority',
  path: '/jira/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraBoardsRoute = JiraBoardsRouteImport.update({
  id: '/jira/boards',
  path: '/jira/boards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/agent-productivity': typeof AgentProductivityRoute
  '/health': typeof HealthRoute
  '/nodes': typeof NodesRoute
  '/prs': typeof PrsRoute
  '/reports': typeof ReportsRoute
  '/system-health': typeof SystemHealthRoute
  '/x-explorer': typeof XExplorerRoute
  '/jira/boards': typeof JiraBoardsRoute
  '/jira/priority': typeof JiraPriorityRoute
  '/timeline/hourly': typeof TimelineHourlyRoute
  '/work/$': typeof WorkSplatRoute
  '/timeline': typeof TimelineIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/agent-productivity': typeof AgentProductivityRoute
  '/health': typeof HealthRoute
  '/nodes': typeof NodesRoute
  '/prs': typeof PrsRoute
  '/reports': typeof ReportsRoute
  '/system-health': typeof SystemHealthRoute
  '/x-explorer': typeof XExplorerRoute
  '/jira/boards': typeof JiraBoardsRoute
  '/jira/priority': typeof JiraPriorityRoute
  '/timeline/hourly': typeof TimelineHourlyRoute
  '/work/$': typeof WorkSplatRoute
  '/timeline': typeof TimelineIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/agent-productivity': typeof AgentProductivityRoute
  '/health': typeof HealthRoute
  '/nodes': typeof NodesRoute
  '/prs': typeof PrsRoute
  '/reports': typeof ReportsRoute
  '/system-health': typeof SystemHealthRoute
  '/x-explorer': typeof XExplorerRoute
  '/jira/boards': typeof JiraBoardsRoute
  '/jira/priority': typeof JiraPriorityRoute
  '/timeline/hourly': typeof TimelineHourlyRoute
  '/work/$': typeof WorkSplatRoute
  '/timeline/': typeof TimelineIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/agent-productivity'
    | '/health'
    | '/nodes'
    | '/prs'
    | '/reports'
    | '/system-health'
    | '/x-explorer'
    | '/jira/boards'
    | '/jira/priority'
    | '/timeline/hourly'
    | '/work/$'
    | '/timeline'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/agent-productivity'
    | '/health'
    | '/nodes'
    | '/prs'
    | '/reports'
    | '/system-health'
    | '/x-explorer'
    | '/jira/boards'
    | '/jira/priority'
    | '/timeline/hourly'
    | '/work/$'
    | '/timeline'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/agent-productivity'
    | '/health'
    | '/nodes'
    | '/prs'
    | '/reports'
    | '/system-health'
    | '/x-explorer'
    | '/jira/boards'
    | '/jira/priority'
    | '/timeline/hourly'
    | '/work/$'
    | '/timeline/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AgentProductivityRoute: typeof AgentProductivityRoute
  HealthRoute: typeof HealthRoute
  NodesRoute: typeof NodesRoute
  PrsRoute: typeof PrsRoute
  ReportsRoute: typeof ReportsRoute
  SystemHealthRoute: typeof SystemHealthRoute
  XExplorerRoute: typeof XExplorerRoute
  JiraBoardsRoute: typeof JiraBoardsRoute
  JiraPriorityRoute: typeof JiraPriorityRoute
  TimelineHourlyRoute: typeof TimelineHourlyRoute
  WorkSplatRoute: typeof WorkSplatRoute
  TimelineIndexRoute: typeof TimelineIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x-explorer': {
      id: '/x-explorer'
      path: '/x-explorer'
      fullPath: '/x-explorer'
      preLoaderRoute: typeof XExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs': {
      id: '/prs'
      path: '/prs'
      fullPath: '/prs'
      preLoaderRoute: typeof PrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-productivity': {
      id: '/agent-productivity'
      path: '/agent-productivity'
      fullPath: '/agent-productivity'
      preLoaderRoute: typeof AgentProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/': {
      id: '/timeline/'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$': {
      id: '/work/$'
      path: '/work/$'
      fullPath: '/work/$'
      preLoaderRoute: typeof WorkSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/hourly': {
      id: '/timeline/hourly'
      path: '/timeline/hourly'
      fullPath: '/timeline/hourly'
      preLoaderRoute: typeof TimelineHourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira/priority': {
      id: '/jira/priority'
      path: '/jira/priority'
      fullPath: '/jira/priority'
      preLoaderRoute: typeof JiraPriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira/boards': {
      id: '/jira/boards'
      path: '/jira/boards'
      fullPath: '/jira/boards'
      preLoaderRoute: typeof JiraBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AgentProductivityRoute: AgentProductivityRoute,
  HealthRoute: HealthRoute,
  NodesRoute: NodesRoute,
  PrsRoute: PrsRoute,
  ReportsRoute: ReportsRoute,
  SystemHealthRoute: SystemHealthRoute,
  XExplorerRoute: XExplorerRoute,
  JiraBoardsRoute: JiraBoardsRoute,
  JiraPriorityRoute: JiraPriorityRoute,
  TimelineHourlyRoute: TimelineHourlyRoute,
  WorkSplatRoute: WorkSplatRoute,
  TimelineIndexRoute: TimelineIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
