/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as ShortlistRouteImport } from './routes/shortlist'
import { Route as RecommendationV1RouteImport } from './routes/recommendation-v1'
import { Route as RecommendationLatestRouteImport } from './routes/recommendation-latest'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as EvelinaRouteImport } from './routes/evelina'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortlistRoute = ShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationV1Route = RecommendationV1RouteImport.update({
  id: '/recommendation-v1',
  path: '/recommendation-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationLatestRoute = RecommendationLatestRouteImport.update({
  id: '/recommendation-latest',
  path: '/recommendation-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvelinaRoute = EvelinaRouteImport.update({
  id: '/evelina',
  path: '/evelina',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/community': typeof CommunityRoute
  '/evelina': typeof EvelinaRoute
  '/findings': typeof FindingsRoute
  '/properties': typeof PropertiesRoute
  '/rankings': typeof RankingsRoute
  '/recommendation-latest': typeof RecommendationLatestRoute
  '/recommendation-v1': typeof RecommendationV1Route
  '/shortlist': typeof ShortlistRoute
  '/tips': typeof TipsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/community': typeof CommunityRoute
  '/evelina': typeof EvelinaRoute
  '/findings': typeof FindingsRoute
  '/properties': typeof PropertiesRoute
  '/rankings': typeof RankingsRoute
  '/recommendation-latest': typeof RecommendationLatestRoute
  '/recommendation-v1': typeof RecommendationV1Route
  '/shortlist': typeof ShortlistRoute
  '/tips': typeof TipsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/budget': typeof BudgetRoute
  '/community': typeof CommunityRoute
  '/evelina': typeof EvelinaRoute
  '/findings': typeof FindingsRoute
  '/properties': typeof PropertiesRoute
  '/rankings': typeof RankingsRoute
  '/recommendation-latest': typeof RecommendationLatestRoute
  '/recommendation-v1': typeof RecommendationV1Route
  '/shortlist': typeof ShortlistRoute
  '/tips': typeof TipsRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/budget'
    | '/community'
    | '/evelina'
    | '/findings'
    | '/properties'
    | '/rankings'
    | '/recommendation-latest'
    | '/recommendation-v1'
    | '/shortlist'
    | '/tips'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/budget'
    | '/community'
    | '/evelina'
    | '/findings'
    | '/properties'
    | '/rankings'
    | '/recommendation-latest'
    | '/recommendation-v1'
    | '/shortlist'
    | '/tips'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/budget'
    | '/community'
    | '/evelina'
    | '/findings'
    | '/properties'
    | '/rankings'
    | '/recommendation-latest'
    | '/recommendation-v1'
    | '/shortlist'
    | '/tips'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  BudgetRoute: typeof BudgetRoute
  CommunityRoute: typeof CommunityRoute
  EvelinaRoute: typeof EvelinaRoute
  FindingsRoute: typeof FindingsRoute
  PropertiesRoute: typeof PropertiesRoute
  RankingsRoute: typeof RankingsRoute
  RecommendationLatestRoute: typeof RecommendationLatestRoute
  RecommendationV1Route: typeof RecommendationV1Route
  ShortlistRoute: typeof ShortlistRoute
  TipsRoute: typeof TipsRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortlist': {
      id: '/shortlist'
      path: '/shortlist'
      fullPath: '/shortlist'
      preLoaderRoute: typeof ShortlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-v1': {
      id: '/recommendation-v1'
      path: '/recommendation-v1'
      fullPath: '/recommendation-v1'
      preLoaderRoute: typeof RecommendationV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-latest': {
      id: '/recommendation-latest'
      path: '/recommendation-latest'
      fullPath: '/recommendation-latest'
      preLoaderRoute: typeof RecommendationLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evelina': {
      id: '/evelina'
      path: '/evelina'
      fullPath: '/evelina'
      preLoaderRoute: typeof EvelinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  BudgetRoute: BudgetRoute,
  CommunityRoute: CommunityRoute,
  EvelinaRoute: EvelinaRoute,
  FindingsRoute: FindingsRoute,
  PropertiesRoute: PropertiesRoute,
  RankingsRoute: RankingsRoute,
  RecommendationLatestRoute: RecommendationLatestRoute,
  RecommendationV1Route: RecommendationV1Route,
  ShortlistRoute: ShortlistRoute,
  TipsRoute: TipsRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
